/**
 * typia utils for OpenAI API
 * @deprecated use typia.llm
 */

import type { ResponseFormatJSONSchema } from "openai/resources/shared";
import {
  type AutoParseableResponseFormat,
  makeParseableResponseFormat,
  makeParseableTool,
} from "openai/lib/parser";
import type typia from "typia";
import type { Primitive } from "typia";

/**
 * Params for `typiaJsonToOpenAIJsonSchema` and `typiaJsonToOpenAIResponse`
 * @deprecated use typia.llm
 */
export interface TypiaJsonToOpenAIJsonSchemaParams<T> {
  /**
   * JSON Schema generated by Typia.
   * @see [`application()` function](https://typia.io/docs/json/schema/)
   */
  jsonSchema: ReturnType<typeof typia.json.application<[T], "3.0" | "3.1">>;

  /**
   * Whether to enable strict schema adherence when generating the output. If set to
   * true, the model will always follow the exact schema defined in the `schema`
   * field. Only a subset of JSON Schema is supported when `strict` is `true`. To
   * learn more, read the
   * [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).
   * @default true
   */
  strict?: boolean | null;
}

/**
 * Params for `typiaResponseFormat`
 * @deprecated use typia.llm
 */
export interface TypiaResponseFormatParams<T>
  extends TypiaJsonToOpenAIJsonSchemaParams<T> {
  /**
   * A validate function generated by Typia.
   * @see [`validate()` function](https://typia.io/docs/validators/validate/)
   */
  validate: (input: unknown) => typia.IValidation<T>;
}

/**
 * Params for `typiaFunction`
 * @deprecated use typia.llm
 */
export interface TypiaFunctionParams<T> extends TypiaResponseFormatParams<T> {
  /**
   * Name of the function.
   * if not specified, it will be the same as the name of the JSON Schema.
   */
  name?: string;
  /**
   * Description of the function.
   * if not specified, it will be the same as the description of the JSON Schema.
   */
  description?: string;

  /**
   * A function that will be called when the model calls the function.
   */
  function?: ((args: T) => unknown | Promise<unknown>) | undefined;
}

/**
 * Converts JSON Schema generated by Typia to OpenAI JSON Schema.
 * Recommended to use `typiaResponseFormat` instead.
 * @see [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).
 * @deprecated use typia.llm
 */
export function typiaJsonToOpenAIJsonSchema<T>(
  { jsonSchema, strict }: TypiaJsonToOpenAIJsonSchemaParams<T>,
): ResponseFormatJSONSchema.JSONSchema {
  const { schemas } = jsonSchema.components;

  if (schemas == null) {
    throw new Error("json_schema.components.schemas is null");
  }

  const name = Object.keys(schemas).at(0);

  if (name == null) {
    throw new Error("name is null");
  }

  const targetSchema = schemas[name];

  return {
    name,
    schema: targetSchema as Record<string, unknown>,
    description: targetSchema.description,
    strict: strict ?? true,
  };
}

/**
 * Converts JSON Schema generated by Typia to OpenAI ResponseFormat for Structured Outputs.
 * recommended to use this function instead of `typiaResponseFormat` instead.
 * @see [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).
 * @deprecated use typia.llm
 *
 * @example
 * ```ts
 * import { typiaJsonToOpenAIResponse } from "@ryoppippi/typiautil/openai";
 * import typia, { tags } from "typia";
 * import OpenAI from "openai";
 *
 * type Output = {
 *   id: string & tags.Type<'uint32'>;
 *
 *   name: string & tags.MinLength<1>;
 * }
 *
 *  const client = new OpenAI({})
 *
 *  const jsonSchema = typia.json.application<[Output]>();
 *  const chat = await client.beta.chat.completions.parse({
 *   model: "gpt-4o-mini",
 *   response_format: typiaJsonToOpenAIResponse({ jsonSchema }),
 *   messages: [
 *     {
 *       role: "system",
 *      content: "Extract information and return as the structured data following schema",
 *     },
 *   ],
 *  });
 * const json = typia.json.validateParse<Output>(chat.choices.at(0)?.message.content as string)
 * ```
 */
export function typiaJsonToOpenAIResponse<T>(
  params: TypiaJsonToOpenAIJsonSchemaParams<T>,
): ResponseFormatJSONSchema {
  return {
    type: "json_schema",
    json_schema: typiaJsonToOpenAIJsonSchema(params),
  };
}

function createParser<T>(validate: ReturnType<typeof typia.createValidate<T>>) {
  return (input: string): Primitive<T> => {
    const json = JSON.parse(input);

    const result = validate(json);
    if (!result.success) {
      throw new Error(`${result.errors.toString()}`);
    }
    return json;
  };
}

/**
 * Creates an AutoParseableResponseFormat for OpenAI API from Typia JSON Schema.
 * @see [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).
 * @deprecated use typia.llm
 *
 * @example
 * ```ts
 * import { typiaResponseFormat } from "@ryoppippi/typiautil/openai";
 * import typia, { tags } from "typia";
 * import OpenAI from "openai";
 *
 * type Output = {
 *   id: string & tags.Type<'uint32'>;
 *   name: string & tags.MinLength<1>;
 * }
 *
 *  const client = new OpenAI({})
 *
 *  const completion = await client.beta.chat.completions.parse({
 *   model: "gpt-4o-mini",
 *   response_format: typiaResponseFormat({
 *     jsonSchema: typia.json.application<[Output]>(),
 *     validate: typia.createValidate<Output>(), // or typia.createValidateEquals<Output>()
 *   }),
 *   messages: [
 *     {
 *       role: "system",
 *      content: "Extract information and return as the structured data following schema",
 *     },
 *   ],
 *  });
 *
 * console.log(completion.choices[0].message.parsed);
 * ```
 */
export function typiaResponseFormat<T>(
  params: TypiaResponseFormatParams<T>,
): AutoParseableResponseFormat<Primitive<T>> {
  type ParsedT = Primitive<T>;

  const response = typiaJsonToOpenAIResponse(params);

  const parser = createParser(params.validate);

  return makeParseableResponseFormat<ParsedT>(response, parser);
}

/**
 * Creates a chat completion `function` tool that can be invoked
 * automatically by the chat completion `.runTools()` method or automatically
 * parsed by `.parse()` / `.stream()`.
 * @deprecated use typia.llm
 *
 * @see [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).
 *
 * @example
 * ```ts
 * import { typiaFunction } from "@ryoppippi/typiautil/openai";
 * import typia, { tags } from "typia";
 * import OpenAI from "openai";
 *
 * // description ( you should write in JSDOC, see README.md )
 * type Params = {
 *   id: string & tags.Type<'uint32'>;
 *   name: string & tags.MinLength<1>;
 * }
 *
 * function myFunction(args: Params) {
 *   return args;
 * }
 *
 * const client = new OpenAI({})
 *
 * const completion = await client.beta.chat.completions.parse({
 *   model: "gpt-4o-mini",
 *   tool: [typiaFunction({
 *     jsonSchema: typia.json.application<[Params]>(),
 *     validate: typia.createValidate<Params>(), // or typia.createValidateEquals<Params>()
 *     name: "dummy", // you can specify the name of the function, otherwise it will be the name of the type (in this case, "Params")
 *     description: "dummy function", // you can specify the description of the function, otherwise it will be the JSDoc of the type (in this case, "add description as a JSDoc")
 *     function: myFunction, // the function to be called (optional)
 *    })],
 *   messages: [
 *     {
 *       role: "system",
 *       content: "use the dummy function",
formation and return as the structured data following schema",
 *     },
 *   ],
 * });
 *
 * console.log(completion.choices[0].message.tool_calls[0].function.parsed_arguments);
 * ```
 */
export function typiaFunction<T>(
  params: TypiaFunctionParams<T>,
): AutoParseableResponseFormat<Record<string, unknown>> {
  const {
    strict,
    name,
    description: _description,
    schema,
  } = typiaJsonToOpenAIJsonSchema(params);

  const parser = createParser(params.validate);

  // @ts-expect-error TODO
  return makeParseableTool<unknown>(
    {
      type: "function",
      function: {
        strict,
        name: params.name ?? name,
        parameters: schema,
        description: params.description ?? _description,
      },
    },
    {
      callback: params.function,
      parser,
    },
  );
}
