import type { ResponseFormatJSONSchema } from "openai/resources/shared";
import {
  type AutoParseableResponseFormat,
  makeParseableResponseFormat,
} from "openai/lib/parser";
import type typia from "typia";

/**
 * Params for `typiaJsonToOpenAIJsonSchema` and `typiaJsonToOpenAIResponse`
 */
export interface TypiaJsonToOpenAIJsonSchemaParams<T> {
  /**
   * A function that returns a JSON Schema object generated by Typia.
   * note: not a JSON Schema object itself, but a function that returns it.
   */
  jsonSchema: ReturnType<typeof typia.json.application<[T]>>;

  /**
   * Whether to enable strict schema adherence when generating the output. If set to
   * true, the model will always follow the exact schema defined in the `schema`
   * field. Only a subset of JSON Schema is supported when `strict` is `true`. To
   * learn more, read the
   * [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).
   */
  strict?: boolean | null;
}

type Primitive<T> = typia.Primitive<T>;

/**
 * Params for `typiaResponseFormat`
 */
interface TypiaResponseFormatParams<T>
  extends TypiaJsonToOpenAIJsonSchemaParams<T> {
  assertParse: ReturnType<typeof typia.json.createAssertParse<T>>;
}

/**
 * Converts JSON Schema generated by Typia to OpenAI JSON Schema.
 * Recommended to use `typiaResponseFormat` instead.
 * @see [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).
 */
export function typiaJsonToOpenAIJsonSchema<T>(
  { jsonSchema, strict }: TypiaJsonToOpenAIJsonSchemaParams<T>,
): ResponseFormatJSONSchema.JSONSchema {
  const { schemas } = jsonSchema.components;

  if (schemas == null) {
    throw new Error("json_schema.components.schemas is null");
  }

  const name = Object.keys(schemas).at(0);

  if (name == null) {
    throw new Error("name is null");
  }

  const targetSchema = schemas[name];

  return {
    name,
    schema: targetSchema as Record<string, unknown>,
    description: targetSchema.description,
    strict,
  };
}

/**
 * Converts JSON Schema generated by Typia to OpenAI ResponseFormat for Structured Outputs.
 * recommended to use this function instead of `typiaResponseFormat` instead.
 * @see [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).
 *
 * @example
 * ```ts
 * import { typiaJsonToOpenAIResponse } from "@ryoppippi/typiautil/openai";
 * import typia from "typia";
 * import OpenAI from "openai";
 *
 * /** add description as a JSDoc \*\/
 * type Output = {
 *   /** id of the entity \*\/
 *   id: string & tags.Type<'uint32'>;
 *
 *   /** name of the entity \*\/
 *   name: string & tags.MinLength<1>;
 * }
 *
 *  const client = new OpenAI({})
 *
 *  const jsonSchema = typia.json.application<[Output]>();
 *  const chat = await client.chat.completions.create({
 *   model: "gpt-4o-mini",
 *   response_format: typiaJsonToOpenAIResponse({ jsonSchema }),
 *   messages: [
 *     {
 *       role: "system",
 *      content: "Extract information and return as the structured data following schema",
 *     },
 *   ],
 *  });
 * ```
 */
export function typiaJsonToOpenAIResponse<T>(
  params: TypiaJsonToOpenAIJsonSchemaParams<T>,
): ResponseFormatJSONSchema {
  return {
    type: "json_schema",
    json_schema: typiaJsonToOpenAIJsonSchema(params),
  };
}

/**
 * Creates an AutoParseableResponseFormat for OpenAI API from Typia JSON Schema.
 * @see [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).
 *
 * @example
 * ```ts
 * import { typiaResponseFormat } from "@ryoppippi/typiautil/openai";
 * import typia from "typia";
 * import OpenAI from "openai";
 *
 * /** add description as a JSDoc \*\/
 * type Output = {
 *   /** id of the entity \*\/
 *   id: string & tags.Type<'uint32'>;
 *
 *   /** name of the entity \*\/
 *   name: string & tags.MinLength<1>;
 * }
 *
 *  const client = new OpenAI({})
 *
 *  const chat = await client.chat.completions.create({
 *   model: "gpt-4o-mini",
 *   response_format: typiaResponseFormat({
 *     jsonSchema: typia.json.application<[Output]>(),
 *     assertParse: typia.json.createAssertParse<Output>(),
 *   }),
 *   messages: [
 *     {
 *       role: "system",
 *      content: "Extract information and return as the structured data following schema",
 *     },
 *   ],
 *  });
 * ```
 */
export function typiaResponseFormat<T>(
  params: TypiaResponseFormatParams<T>,
): AutoParseableResponseFormat<Primitive<T>> {
  type ParsedT = Primitive<T>;

  const response = typiaJsonToOpenAIResponse(params);

  return makeParseableResponseFormat<ParsedT>(response, params.assertParse);
}
